// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdszYTz3vRsRsZcWL8nX6Q0N_aQZJf1I',
    appId: '1:134717164052:web:4f3e7d8c45ee89b1e7b501',
    messagingSenderId: '134717164052',
    projectId: 'presupuesto-familiar-ee8eb',
    authDomain: 'presupuesto-familiar-ee8eb.firebaseapp.com',
    storageBucket: 'presupuesto-familiar-ee8eb.appspot.com',
    measurementId: 'G-L0L9P5WHH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGcWpzQlymKgADtCPQXMaMvIGZweheYI',
    appId: '1:134717164052:android:029dd21995a1d1f1e7b501',
    messagingSenderId: '134717164052',
    projectId: 'presupuesto-familiar-ee8eb',
    storageBucket: 'presupuesto-familiar-ee8eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_76fLGbdtQ2rdux0nGWLMpR1WVTvnrpo',
    appId: '1:134717164052:ios:17967d31d8ec33ffe7b501',
    messagingSenderId: '134717164052',
    projectId: 'presupuesto-familiar-ee8eb',
    storageBucket: 'presupuesto-familiar-ee8eb.appspot.com',
    iosBundleId: 'com.example.presupuestoFamiliar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_76fLGbdtQ2rdux0nGWLMpR1WVTvnrpo',
    appId: '1:134717164052:ios:17967d31d8ec33ffe7b501',
    messagingSenderId: '134717164052',
    projectId: 'presupuesto-familiar-ee8eb',
    storageBucket: 'presupuesto-familiar-ee8eb.appspot.com',
    iosBundleId: 'com.example.presupuestoFamiliar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtdszYTz3vRsRsZcWL8nX6Q0N_aQZJf1I',
    appId: '1:134717164052:web:4107d2ba83dc7b96e7b501',
    messagingSenderId: '134717164052',
    projectId: 'presupuesto-familiar-ee8eb',
    authDomain: 'presupuesto-familiar-ee8eb.firebaseapp.com',
    storageBucket: 'presupuesto-familiar-ee8eb.appspot.com',
    measurementId: 'G-VLQPMT44NF',
  );

}